### ISSUE TITLE
Update cloudflared

### ISSUE THREAD

**Issue by baudneo** [mimugmail/opn-repo#175]
Cloudflared allows remote tunnel management in newer versions of cloudflared. It would be great to have a binary that supports that option as CloudFlare is constantly breaking cloudflared management.

As an example, you can no longer login to cloudflared using `cloudflared tunnel login` which makes it impossible to use or manage any argo tunnels because local management is unsupported without `tunnel login`. A new binary would allow remote management tunnels to work.

**Comment by mimugmail** [comment]
I need some beta testers for Unifi upgrade, already have the updated pkg in beta channel

**Comment by baudneo** [comment]
How can I switch to the beta channel for mimugmail repo only?

**Comment by mimugmail** [comment]
You edit the mimugmail.conf and replace /repo with /transfer and search for updates again

**Comment by mihakralj** [comment]
switch to beta channel:
`sudo sed -i '' 's|/repo/|/transfer/|g' /usr/local/etc/pkg/repos/mimugmail.conf`

switch to main channel:
`sudo sed -i '' 's|/transfer/|/repo/|g' /usr/local/etc/pkg/repos/mimugmail.conf`

**Comment by baudneo** [comment]
Cloudflared is stuck on the same version except a minor bump to _4. Bsd is also stuck at this version so I am assuming it's dependant on freebsd and their releases? 

I can't seem to compile it myself either, not much experience with bsd.

**Comment by Salsa0780** [comment]
@baudneo running into the same problem not being able to run `cloudflared service install` Were you able to find a solution?

**Comment by baudneo** [comment]
@Salsa0780 I spun up a lxc in proxmox and have cloudflared hosted in a docker container.

**Comment by Salsa0780** [comment]
@baudneo thanks for the quick reply! I did manage to get it working. It seems the issue is with cloudflared itself not providing service support for BSD/rc.d (only Systemd and SysV), instead of a problem with the build provided here. See here: https://github.com/cloudflare/cloudflared/blob/33baad35b8d2d99dda35617a25b73ad0bcc4e6f9/cmd/cloudflared/linux_service.go#L229C2-L229C2

I ended up following a combination of this [reddit thread](https://www.reddit.com/r/opnsense/comments/12grq78/cant_get_cloudflared_service_to_start_on_boot/) and this [example repo](https://github.com/davidmytton/cloudflared-freebsd) to manually create the service. Seems there is already a somewhat fleshed out config file here as well: `/usr/local/etc/rc.d/cloudflared`

finally, I was able to connect it up to a remotely managed tunnel by base64 decoding the string provided in the web GUI and copying into the `<tag-UUID>.json` file:

```python
import base64

# from cloudflare tunnels dashboard `sudo cloudflared service install eyJhIjoidGhpcy1pcy10aGUtYWNjb3VudFRhZyIsInQiOiJ0aGlzLWlzLXRoZS10dW5uZWwtdXVpZCIsInMiOiJ0aGlzLWlzLXRoZS10dW5uZWwtc2VjcmV0In0=`
tunnel_creds_b64 = "eyJhIjoidGhpcy1pcy10aGUtYWNjb3VudFRhZyIsInQiOiJ0aGlzLWlzLXRoZS10dW5uZWwtdXVpZCIsInMiOiJ0aGlzLWlzLXRoZS10dW5uZWwtc2VjcmV0In0="
plain_text = base64.b64decode(tunnel_creds_b64)
print(plain_text)
# > b'{"a":"this-is-the-accountTag","t":"this-is-the-tunnel-uuid","s":"this-is-the-tunnel-secret"}'
```

**Comment by sammyke007** [comment]
I'm running cloudflared as explained here using the port:

https://www.jackpearce.co.uk/cloudflared-opnsense/

This port is outdated (2023.10) and don't get updated that quickly. Can I change it to using the cloudflared from your repo without problems?
