### ISSUE TITLE
Speedtest plugin

### ISSUE THREAD

**Issue by mimugmail** [mimugmail/opn-repo#26]
New addition

**Comment by mimugmail** [comment]
@mihakralj I renamed the plugin to speedtest-mihakralj. Is this ok for you?
Since the community repo is growing I want to make it clear that plugins maintained by my are called "-maxit" (my employer) and others by their maintainers. So you System : Firmware : Plugins, you'll see the repo-name mimugmail and the pluginname with it's author.

**Comment by mihakralj** [comment]
that is awesome, thanks for hosting it!

**Comment by mimugmail** [comment]
I added it now to the repo. 
If we announce this on reddit we have to make sure to tell guys that they have to uninstall the orphaned version before. 
Can you test the version of the repo so I can make this public?

**Comment by mihakralj** [comment]
I will update the widget from using PHP (that is **FAST**) back to using js ajax (that auto-refreshes).
Let me PR that first (just one file change), then we can test it to oblivion.

**Comment by mihakralj** [comment]
![image](https://user-images.githubusercontent.com/31756078/113908522-80acf900-978b-11eb-9faf-8f212b23ff58.png)

This naming is a bit too... Personal. :-)
I understand we need to separate -maxit plugins from kludges that will be accepted by a community, but we should find a better naming convention.

How about:
- we use suffix _-community_ to name packages
- we expect a name, email and direct link to github repo being part of the package description in mimugmail repo
- add some disclaimer that _-community_ plugins can harm you and encourage people to review/validate the source code before they take the plunge

If you'd still prefer an explicit name as part of the package, I'd rather go with your pattern and use mihak09 (my gmail account) as a prefix, just like you use mimugmail instead of your full name.

**Comment by mihakralj** [comment]
Oh, and you should see two PRs to update the widget to the ajax-based one.

**Comment by mimugmail** [comment]
Ok updated the widget, renamed plugin and bumped to 0.9.
Can you test again please?

**Comment by mihakralj** [comment]
not visible yet:
![image](https://user-images.githubusercontent.com/31756078/113971375-83403a80-97ed-11eb-88fa-c4e0cc264a41.png)

**Comment by mimugmail** [comment]
Did you check for updates?

**Comment by mimugmail** [comment]
OK, now rerun update check

**Comment by mihakralj** [comment]
Visible, updating and checking!
![image](https://user-images.githubusercontent.com/31756078/113974413-bd600b00-97f2-11eb-96b7-c4c68008bf6a.png)

**Comment by mihakralj** [comment]
seems to work on both physical and one VM. 👍

**Comment by mimugmail** [comment]
Indeed, looks good. Do you want to announce it on reddit or shall I? If you do, please mention that before installing it, one needs to remove the existing one via System : Firmware : Plugins

**Comment by mihakralj** [comment]
Feel free to announce it - you are the maintainer! 😊

I can write something tomorrow morning if needed (I am based in Redmond/Seattle)

**Comment by mimugmail** [comment]
https://www.reddit.com/r/OPNsenseFirewall/comments/mmmtkx/speedtest_plugin_now_in_community_repo_available/
